language: python

sudo: false

python:
 - "2.7"
 - "3.5"

env:
 - DJANGO_VERSION=1.8.8 DATABASE_SETTINGS='settings_test_mysql.py'
 - DJANGO_VERSION=1.8.8 DATABASE_SETTINGS='settings_test_postgresql.py'
 - DJANGO_VERSION=1.8.8 DATABASE_SETTINGS='settings_test_multi_dbs.py'
 - DJANGO_VERSION=1.9.1 DATABASE_SETTINGS='settings_test_mysql.py'
 - DJANGO_VERSION=1.9.1 DATABASE_SETTINGS='settings_test_postgresql.py'
 - DJANGO_VERSION=1.9.1 DATABASE_SETTINGS='settings_test_multi_dbs.py'

install:
 - pip install -r requirements_dev.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

before_script:
  - mysql -e 'create database calaccess_raw;'
  - psql -c 'create database calaccess_raw;' -U postgres
  - cp example/$DATABASE_SETTINGS.template example/settings_local.py

script:
 - pep8 calaccess_raw
 - pyflakes calaccess_raw
 - python example/manage.py makemigrations calaccess_raw
 - python example/manage.py migrate
 - python example/manage.py createcalaccessrawmodeldocs
 - cd docs && make html && cd ..
 - coverage run example/manage.py test calaccess_raw

after_success:
 - coveralls
