language: python
python:
 - "2.7"
env:
 - DJANGO_VERSION=1.4.10
 - DJANGO_VERSION=1.5.4
 - DJANGO_VERSION=1.6.5
install:
 - pip install pep8 pyflakes coverage python-coveralls
 - pip install -q Django==$DJANGO_VERSION
 - python setup.py install
script:
 - pep8 calaccess
 - pyflakes calaccess
 - coverage run setup.py test
after_success:
 - coveralls
